---
- name: Arista Ansible testing
  hosts: arista

  tasks:
    - name: Changing Eth4 description
      eos_interface: name=Ethernet4 description="*** IN USE ***"
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    - name: Set Eth4 to access, VLAN222
      eos_switchport: name=Ethernet4 mode=access access_vlan=222 trunk_allowed_vlans=all
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

