---
- name: Arista Ansible testing
  hosts: arista

  tasks:
    - name: Changing Eth4 description to default
      eos_interface: name=Ethernet4 admin=enable null_as_default=true
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    - name: Set Eth4 mode, allowed vlans to default
      eos_switchport: name=Ethernet4 mode=access access_vlan=1 trunk_allowed_vlans=all
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

    - name: Remove newly-created VLANs
      eos_vlan: name={{ item.name }} vlanid={{ item.vlanid }} state=unconfigured
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

      with_items:
        - {name: bluebarry, vlanid: 111}
        - {name: cherry, vlanid: 222}
        - {name: lime, vlanid: 333}

