---
- name: Arista Ansible testing
  hosts: arista

  tasks:
    - name: Set Ethernet4 to trunk native VL1, allow 111,222,333
      eos_switchport: name=Ethernet4 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=111,222,333
            eapi_username={{ eapi_username }}
            eapi_password={{ eapi_password }}
            eapi_hostname={{ eapi_hostname }}
            eapi_port={{ eapi_port }}

